---
Name: cwpconfig
After: 'cwp-core/*'
---
SiteConfig:
  extensions:
   - CustomSiteConfig
TaxonomyTerm:
  extensions:
   - TaxonomyTermExtension
---
Name: cwpuploadextensions
Only:
  moduleexists: 'selectupload'
---
Injector:
  UploadField: SelectUploadField
