---
Name: cwpconfig
After: 'cwp-core/*'
---
SiteConfig:
  extensions:
   - CustomSiteConfig
TaxonomyTerm:
  extensions:
   - TaxonomyTermExtension
Member:
  title_format:
    columns:
      - FirstName
      - Surname
    sep: ' '
---
Name: cwpsitetreefileextensions
---
Injector:
  SiteTreeFileExtension: CwpSiteTreeFileExtension
---
Name: mimeuploadvalidator
Only:
  moduleexists: 'mimevalidator'
---
Injector:
  Upload_Validator:
    class: MimeUploadValidator
---
Name: cwpuploadextensions
Only:
  moduleexists: 'selectupload'
---
Injector:
  UploadField: SelectUploadField
---
Name: cwpspellcheck
Only:
  moduleexists: 'spellcheck'
---
SpellRequestFilter:
  editor: 'cwp'
SpellController:
  locales:
    - en_NZ
    - mi_NZ
---
Name: cwpworkflowextensions
Only:
  moduleexists: 'advancedworkflow'
---
WorkflowDefinition:
  extensions:
    - CwpWorkflowDefinitionExtension
---
Name: cwpcommentingextensions
Only:
  moduleexists: 'comments'
---
CommentingController:
  extensions:
    - CwpCommentingExtension
