---
Name: cwpconfig
After: 'framework/*','cms/*'
---
DBField:
  extensions:
   - RichLinksExtension
Controller:
  extensions:
   - CwpControllerExtension
SiteConfig:
  extensions:
   - CustomSiteConfig
Group:
  extensions:
   - CwpHtmlEditorConfig
HtmlEditorField_Toolbar:
  extensions:
   - CustomHtmlEditorFieldToolbar
TaxonomyTerm:
  extensions:
   - TaxonomyTermExtension
GDBackend:
  default_quality: 90
LeftAndMain:
  extra_requirements_css:
   - 'cwp/css/custom.css'
Session:
  timeout: 3600
LeftAndMain:
  session_keepalive_ping: false
PasswordField:
  autocomplete: false
