---
Name: cwpconfig
After: 'cwp-core/*'
---
SiteConfig:
  extensions:
   - CustomSiteConfig
TaxonomyTerm:
  extensions:
   - TaxonomyTermExtension
Injector:
  Upload_Validator:
    class: CwpUpload_Validator
---
Name: cwpuploadextensions
Only:
  moduleexists: 'selectupload'
---
Injector:
  UploadField: SelectUploadField
---
Name: cwpspellcheck
Only:
  moduleexists: 'spellcheck'
---
SpellRequestFilter:
  editor: 'cwp'
SpellController:
  locales:
    - en_NZ
    - mi_NZ
