---
Name: cwpconfig
After: 'framework/*','cms/*'
---
DBField:
  extensions:
   - RichLinksExtension
Controller:
  extensions:
   - CwpControllerExtension
SiteConfig:
  extensions:
   - CustomSiteConfig
Group:
  extensions:
   - CwpHtmlEditorConfig
HtmlEditorField_Toolbar:
  extensions:
   - CustomHtmlEditorFieldToolbar
TaxonomyTerm:
  extensions:
   - TaxonomyTermExtension
GDBackend:
  default_quality: 90
LeftAndMain:
  extra_requirements_css:
   - 'cwp/css/custom.css'
Session:
  timeout: 3600
LeftAndMain:
  session_keepalive_ping: false
PasswordField:
  autocomplete: false
Security:
  login_recording: false
---
Except:
  CWP_ENVIRONMENT: prod
---
BasicAuth:
    entire_site_protected: true
    entire_site_protected_code: null
    entire_site_protected_message: "Please log in with your CMS credentials"
